# These are supported funding model platforms
---
github: [ futaura, jens-maus ]
custom: [ "https://www.paypal.com/donate/?hosted_button_id=KSG49RVGY8AG2", "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RAQSDY9YNZVCL" ]