sudo: required
dist: trusty

language: c

# send build/failure notifications
# only on a status change
notifications:
  email:
    on_success: change
    on_failure: change

# download and install our required cross compilers
install:
  # unset CC or our build will break
  - test -n ${CC} && unset CC
  # Make sure we can install i386 packages as some adtools binaries
  # requires i386 libraries being installed to work in the 64bit env
  # of Travis
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update || true
  - sudo apt-get -qq install libc6:i386
  # Install all adtools related stuff we need
  - curl -L https://dl.bintray.com/jens-maus/adtools/adtools-utils.tar.bz2 | sudo tar xj -C /
  - if [[ "${OS}" == "os3" ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-m68k-amigaos.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ "${OS}" == "os4" ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-amigaos-legacy.tar.bz2 | sudo tar xj -C / ; fi
  - if [[ "${OS}" == "mos" ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-morphos.tar.bz2 | sudo tar xj -C / ; fi

# set the PATH variable to the directories the cross compilers are installed.
before_script:
  - export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:/opt/ppc-amigaos/bin:/opt/ppc-morphos/bin:${PATH}

# specify a list of variables to test (here we test the build for our supported
# list of operating systems).
env:
  - OS=os4
  - OS=os4 DEBUG=
  - OS=os3
  - OS=os3 DEBUG=
  - OS=mos
  - OS=mos DEBUG=

# the build command to execute for each test
script:
  - make OS=${OS} -j1
