# Upload latest AmiSSL release to Aminet
name: Aminet Upload

on:
  workflow_dispatch:

jobs:

  ## Setup
  upload:
    name: Check & Upload
    runs-on: ubuntu-latest

    steps:
    - name: Download latest release files
      uses: dawidd6/action-download-artifact@v9
      with:
        workflow: release.yml
        name: release-*
        name_is_regexp: true

    - name: Identify & Upload
      shell: bash
      run: |
         DIR=$(ls | grep release-)
         echo "$DIR"
         VERSION=$(echo $DIR | grep -oP "\-\K\d+\.\d+")
         echo "$VERSION"
