# Upload latest AmiSSL release to Aminet
name: Aminet Upload

on:
  workflow_dispatch:

jobs:

  ## Setup
  upload:
    name: Check & Upload
    runs-on: ubuntu-latest

    steps:
    - name: Download latest release files
      uses: dawidd6/action-download-artifact@v9
      with:
        workflow: release.yml
        name: release-*
        name_is_regexp: true

    - name: Identify & Upload
      run: |
        DIR=$(ls | grep release-)
        VERSION=$(echo $DIR | grep -oP "\-\K\d+\.\d+")
        AMINET_VERSION=$(curl https://aminet.net/util/libs/AmiSSL-v5-SDK.readme | grep -oP "Version:\s+\K\d+\.\d+")
        if $(dpkg --compare-versions $AMINET_VERSION "lt" $VERSION); then
          curl -T "{$(echo $DIR/*.lha $DIR/*.readme | tr ' ' ',')}" -u "aminet@futaura.uk:aminettest1234" ftp://mx.futaura.uk/new
        fi
