name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 480

    strategy:
      fail-fast: false
      matrix:
        #platform: [os4, os3, mos, aros-ppc, aros-i386, aros-x86_64]
        platform: [os4, os3-68020, os3-68060, release]
        build: [release]

        exclude:
          - platform: release
            build: debug

    steps:
    - uses: actions/checkout@v2

    - name: setup dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y -qq || true
        sudo apt-get -qq install libc6:i386
        sudo ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4

    - name: install adtools build env
      run: |
        curl -L https://dl.bintray.com/jens-maus/adtools/adtools-utils.tar.bz2 | sudo tar xj -C /
        if [[ ${{ matrix.platform }} =~ os3-68020|os3-68060|release|nightly ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-m68k-amigaos.tar.bz2 | sudo tar xj -C / ; fi
        if [[ ${{ matrix.platform }} =~ os4|release|nightly ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-amigaos.tar.bz2 | sudo tar xj -C / ; fi
        #if [[ ${{ matrix.platform }} =~ mos|release|nightly ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-morphos.tar.bz2 | sudo tar xj -C / ; fi
        #if [[ ${{ matrix.platform }} =~ aros-ppc|release|nightly ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-ppc-aros.tar.bz2 | sudo tar xj -C / ; fi
        #if [[ ${{ matrix.platform }} =~ aros-i386|release|nightly ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-i386-aros.tar.bz2 | sudo tar xj -C / ; fi
        #if [[ ${{ matrix.platform }} =~ aros-x86_64|release|nightly ]]; then curl -L https://dl.bintray.com/jens-maus/adtools/adtools-x86_64-aros.tar.bz2 | sudo tar xj -C / ; fi

    #- name: cleanup old action artifacts
    #  run: .github/workflows/purge_artifacts.sh ${{ secrets.REPO_ACCESS_TOKEN }}

    #- name: remote debug tmate session
    #  uses: mxschmitt/action-tmate@v1
    #  if: matrix.platform == 'os4'

    - name: build ${{ matrix.platform }}-${{ matrix.build }}
      if: matrix.platform != 'release' && matrix.platform != 'debug'
      timeout-minutes: 480
      run: |
        export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:/opt/ppc-amigaos/bin:/opt/ppc-morphos/bin:${PATH}
        if [[ ${{ matrix.build }} =~ release ]]; then make -j1 OS=${{ matrix.platform }} DEBUG= ; fi
        if [[ ${{ matrix.build }} =~ debug ]]; then make -j1 OS=${{ matrix.platform }} ; fi

    - name: build release
      if: matrix.platform == 'release'
      timeout-minutes: 480
      run: |
        export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:/opt/ppc-amigaos/bin:/opt/ppc-morphos/bin:${PATH}
        make -j1 release
