# AmiSSL Release build
name: Release Build

on:
  workflow_dispatch:

env:
  ADTOOLS_DL_PATH: https://github.com/adtools/adtools/releases/download/20170213
  ADTOOLS_UTILS_DL: https://github.com/adtools/adtools/releases/download/20220416/adtools-utils.tar.bz2

jobs:

  ## Setup
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      osslversion: ${{ steps.env.outputs.osslversion }}
      version: ${{ steps.env.outputs.version }}
      date: ${{ steps.env.outputs.date }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get versions
      shell: bash
      run: |
        BUILD_DATE=$(date +%Y%m%d)
        VERSION=$(grep ^VERSION= Makefile | awk -F= '{ print $2 }')
        REVISION=$(grep ^REVISION= Makefile | awk -F= '{ print $2 }')
        OSSLMAJOR=$(grep ^MAJOR= openssl/VERSION.dat | awk -F= '{ print $2 }')
        OSSLMINOR=$(grep ^MINOR= openssl/VERSION.dat | awk -F= '{ print $2 }')
        OSSLPATCH=$(grep ^PATCH= openssl/VERSION.dat | awk -F= '{ print $2 }')
        echo "osslversion=${OSSLMAJOR}.${OSSLMINOR}" >> $GITHUB_OUTPUT
        echo "version=${VERSION}.${REVISION}" >> $GITHUB_OUTPUT
        echo "date=${BUILD_DATE}" >> $GITHUB_OUTPUT
        echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "GITHUB_SHA7=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

  ## Build OS3 68020-40
  build_os3_020:
    name: Build OS3 68020
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 480
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup dependencies
      if: false
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y -qq || true
        sudo apt-get -qq install libc6:i386
        sudo ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4

    - name: Install adtools build env
      run: |
        curl -L ${{ env.ADTOOLS_UTILS_DL }} | sudo tar xj -C /
        curl -L ${{ env.ADTOOLS_DL_PATH }}/adtools-m68k-amigaos.tar.bz2 | sudo tar xj -C /

    - name: Compile release
      timeout-minutes: 480
      run: |
        export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:${PATH}
        make -j1 OS=os3-68020 DEBUG=

    - name: Upload build files as a workflow artifact
      uses: actions/upload-artifact@v4
      with:
        path: build_os3-68020/
        name: build-${{ needs.setup.outputs.version }}-${{ env.GITHUB_SHA7 }}-os3-020.tgz

  ## Build OS3 68060
  build_os3_060:
    name: Build OS3 68060
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 480
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup dependencies
      if: false
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y -qq || true
        sudo apt-get -qq install libc6:i386
        sudo ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4

    - name: Install adtools build env
      run: |
        curl -L ${{ env.ADTOOLS_UTILS_DL }} | sudo tar xj -C /
        curl -L ${{ env.ADTOOLS_DL_PATH }}/adtools-m68k-amigaos.tar.bz2 | sudo tar xj -C /

    - name: Compile release
      timeout-minutes: 480
      run: |
        export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:${PATH}
        make -j1 OS=os3-68060 DEBUG=

    - name: Upload build files as a workflow artifact
      uses: actions/upload-artifact@v4
      with:
        path: build_os3-68060/
        name: build-${{ needs.setup.outputs.version }}-${{ env.$GITHUB_SHA7 }}-os3-060.tgz

  ## Build OS4
  build_os4:
    name: Build OS4 + Docs
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 480
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup dependencies
      if: false
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y -qq || true
        sudo apt-get -qq install libc6:i386
        sudo ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4

    - name: Install adtools build env
      run: |
        curl -L ${{ env.ADTOOLS_UTILS_DL }} | sudo tar xj -C /
        curl -L ${{ env.ADTOOLS_DL_PATH }}/adtools-ppc-amigaos-legacy.tar.bz2 | sudo tar xj -C /

    - name: Compile release
      timeout-minutes: 480
      run: |
        export PATH=/usr/local/amiga/bin:${PATH}
        make -j1 OS=os4 DEBUG= all build_docs

    - name: Upload build files as a workflow artifact
      uses: actions/upload-artifact@v4
      with:
        path: build_os4/
        name: build-${{ needs.setup.outputs.version }}-${{ env.GITHUB_SHA7 }}-os4.tgz

  ## Create draft release
  release_draft:
    name: Create Draft Release
    runs-on: ubuntu-latest
    timeout-minutes: 480
    needs: [ setup, build_os3_020, build_os3_060, build_os4 ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download all builds
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Setup dependencies
#      if: false
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y -qq || true
        sudo apt-get -qq install libc6:i386
        sudo ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4

    - name: Install adtools build env
      run: |
        curl -L ${{ env.ADTOOLS_DL_PATH }}/adtools-m68k-amigaos.tar.bz2 | sudo tar xj -C /
        curl -L ${{ env.ADTOOLS_DL_PATH }}/adtools-ppc-amigaos.tar.bz2 | sudo tar xj -C /
        #curl -L ${{ env.ADTOOLS_DL_PATH }}/adtools-ppc-morphos.tar.bz2 | sudo tar xj -C /
        #curl -L ${{ env.ADTOOLS_DL_PATH }}/adtools-ppc-aros.tar.bz2 | sudo tar xj -C /
        #curl -L ${{ env.ADTOOLS_DL_PATH }}/adtools-i386-aros.tar.bz2 | sudo tar xj -C /
        #curl -L ${{ env.ADTOOLS_DL_PATH }}/adtools-x86_64-aros.tar.bz2 | sudo tar xj -C /

    - name: Build AmiSSL release archives
      run: |
        ls -las
        export PATH=/usr/local/amiga/bin:/opt/m68k-amigaos/bin:/opt/ppc-amigaos/bin:/opt/ppc-morphos/bin:${PATH}
        ./tools/mkrelease.sh

    - name: Get previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1.4

    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.3.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate release notes
      shell: bash
      run: |
        export CHANGELOG="$(tac <<'EOF'
        ${{ steps.changelog.outputs.changelog }}
        EOF
        )"
        export CHANGELOG="$(awk '
          BEGIN { lines=0 }
          {
            if (/^\s*-|\+/) {
              if (lines++ > 0) printf "\n";
              printf $0
            } else if (lines > 0) {
              if (/^$/) exit
              $1=$1
              printf " %s", $0
            }
          }
          END { printf "\n" }
        ' < CHANGES.md )";
        export VERSION=${{ needs.setup.outputs.version }}
        export PREVIOUS_TAG=${{ steps.previoustag.outputs.tag }}
        export OSSLVERSION=${{ needs.setup.outputs.osslversion }}
        export SHA256SUM="$(cat AmiSSL-${{ needs.setup.outputs.version }}-*.lha.sha256)"
        envsubst <.github/release-template.md >/tmp/release-template.md

    - name: Create release draft
      uses: ncipollo/release-action@v1.16.0
      with:
        tag: ${{ needs.setup.outputs.version }}
        name: 'AmiSSL ${{ needs.setup.outputs.version }}'
        bodyFile: /tmp/release-template.md
        draft: true
        prerelease: false
        allowUpdates: true
        artifacts: AmiSSL-${{ needs.setup.outputs.version }}-*.lha
        artifactContentType: application/x-lha
        token: ${{ secrets.GITHUB_TOKEN }}
